package GUI;


import GUI.GUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tom
 */
public class nodeOptions extends javax.swing.JFrame {

    public GraphNode SelectedNode = null;
    private GUI gui = null;
    public Graph currentGraph = null;

    /**
     * Creates new form nodeOptions
     */
    public nodeOptions(GraphNode node, Graph graph, GUI gui) {
        this.gui = gui;
        currentGraph = graph;
        SelectedNode = node;

        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();

        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new NodeOptionsListener(this.gui));
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        this.setTitle("Options for: "+SelectedNode.getName());
        this.setIconImage(gui.getImg());
        this.setLocation((screensize.width / 2) - (this.getWidth() / 2), (screensize.height / 2) - (this.getHeight() / 2));

        txt_NodeName.setText(node.getName());
        txt_NodeName.setBackground(Color.WHITE);
        txt_NodeX.setText(""+node.getX());
        txt_NodeX.setBackground(Color.WHITE);
        txt_NodeY.setText(""+node.getY());
        txt_NodeY.setBackground(Color.WHITE);

        txt_ndeSize.setText(""+node.getWidth());
        slide_ndeSlider.setValue(node.getWidth());

        if(!currentGraph.Algorithm.equals(GUI.algoType.dijkstras)){
            NodeOptionsPanel.setVisible(false);
        }
        this.pack();
    }

    public void refresh(){
        txt_NodeName.setText(SelectedNode.getName());
        this.gui.update(gui.getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NodeInfoPanel = new javax.swing.JPanel();
        lbl_NodeName = new javax.swing.JLabel();
        txt_NodeName = new javax.swing.JTextField();
        lbl_NodeLocation = new javax.swing.JLabel();
        txt_NodeX = new javax.swing.JTextField();
        txt_NodeY = new javax.swing.JTextField();
        btn_EDITNAME = new javax.swing.JButton();
        NodeCompletetionPanel = new javax.swing.JPanel();
        btn_ResetAndClose = new javax.swing.JButton();
        btn_DeleteNode = new javax.swing.JButton();
        btn_SaveAndExit = new javax.swing.JButton();
        NodeOptionsPanel = new javax.swing.JPanel();
        btn_SetAsGoal = new javax.swing.JToggleButton();
        btn_SetAsRoot = new javax.swing.JToggleButton();
        slide_ndeSlider = new javax.swing.JSlider();
        label_ndeSize = new javax.swing.JLabel();
        txt_ndeSize = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_NodeName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_NodeName.setText("Node Name:");

        txt_NodeName.setEditable(false);
        txt_NodeName.setText("jTextField1");
        txt_NodeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NodeNameActionPerformed(evt);
            }
        });
        txt_NodeName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_NodeNameInputMethodTextChanged(evt);
            }
        });

        lbl_NodeLocation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_NodeLocation.setText("Node Pos:");

        txt_NodeX.setEditable(false);
        txt_NodeX.setText("jTextField1");

        txt_NodeY.setEditable(false);
        txt_NodeY.setText("jTextField1");

        btn_EDITNAME.setText("Edit Name");
        btn_EDITNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EDITNAMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NodeInfoPanelLayout = new javax.swing.GroupLayout(NodeInfoPanel);
        NodeInfoPanel.setLayout(NodeInfoPanelLayout);
        NodeInfoPanelLayout.setHorizontalGroup(
            NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NodeInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NodeInfoPanelLayout.createSequentialGroup()
                        .addGroup(NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_NodeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_NodeLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NodeInfoPanelLayout.createSequentialGroup()
                                .addComponent(txt_NodeX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_NodeY, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_NodeName)))
                    .addComponent(btn_EDITNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NodeInfoPanelLayout.setVerticalGroup(
            NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NodeInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NodeInfoPanelLayout.createSequentialGroup()
                        .addComponent(lbl_NodeName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_NodeName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NodeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NodeLocation)
                    .addComponent(txt_NodeX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NodeY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_EDITNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_ResetAndClose.setText("Reset");
        btn_ResetAndClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetAndCloseActionPerformed(evt);
            }
        });

        btn_DeleteNode.setText("Delete Node");

        btn_SaveAndExit.setText("Save and Close");

        javax.swing.GroupLayout NodeCompletetionPanelLayout = new javax.swing.GroupLayout(NodeCompletetionPanel);
        NodeCompletetionPanel.setLayout(NodeCompletetionPanelLayout);
        NodeCompletetionPanelLayout.setHorizontalGroup(
            NodeCompletetionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NodeCompletetionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NodeCompletetionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NodeCompletetionPanelLayout.createSequentialGroup()
                        .addComponent(btn_ResetAndClose, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_DeleteNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_SaveAndExit, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addContainerGap())
        );
        NodeCompletetionPanelLayout.setVerticalGroup(
            NodeCompletetionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NodeCompletetionPanelLayout.createSequentialGroup()
                .addGroup(NodeCompletetionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ResetAndClose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DeleteNode, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SaveAndExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_SetAsGoal.setText("Set as Goal");

        btn_SetAsRoot.setText("Set as Root");

        javax.swing.GroupLayout NodeOptionsPanelLayout = new javax.swing.GroupLayout(NodeOptionsPanel);
        NodeOptionsPanel.setLayout(NodeOptionsPanelLayout);
        NodeOptionsPanelLayout.setHorizontalGroup(
            NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_SetAsRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SetAsGoal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        NodeOptionsPanelLayout.setVerticalGroup(
            NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NodeOptionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NodeOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SetAsGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SetAsRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        slide_ndeSlider.setMajorTickSpacing(10);
        slide_ndeSlider.setMaximum(160);
        slide_ndeSlider.setMinimum(40);
        slide_ndeSlider.setMinorTickSpacing(2);
        slide_ndeSlider.setPaintTicks(true);
        slide_ndeSlider.setValue(72);
        slide_ndeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slide_ndeSliderStateChanged(evt);
            }
        });

        label_ndeSize.setText("Node Size:");

        txt_ndeSize.setEditable(false);
        txt_ndeSize.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NodeCompletetionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NodeInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NodeOptionsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ndeSize)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_ndeSize)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(slide_ndeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NodeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_ndeSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ndeSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slide_ndeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NodeOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NodeCompletetionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label_ndeSize.getAccessibleContext().setAccessibleName("label_ndeSize");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NodeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NodeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NodeNameActionPerformed

    private void txt_NodeNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_NodeNameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NodeNameInputMethodTextChanged

    private void btn_ResetAndCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetAndCloseActionPerformed
        // TODO add your handling code here:
        SelectedNode.isNamed = false;
        gui.update(gui.getGraphics());
        this.dispose();
    }//GEN-LAST:event_btn_ResetAndCloseActionPerformed

    private void btn_EDITNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EDITNAMEActionPerformed
        // TODO add your handling code here:
        new Keyboard(this).setVisible(true);
    }//GEN-LAST:event_btn_EDITNAMEActionPerformed

    private void slide_ndeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slide_ndeSliderStateChanged
    // TODO add your handling code here:
        txt_ndeSize.setText(""+slide_ndeSlider.getValue());
    }//GEN-LAST:event_slide_ndeSliderStateChanged

    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nodeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nodeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nodeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nodeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         *
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new nodeOptions().setVisible(true);
            }
        });
    }//*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NodeCompletetionPanel;
    private javax.swing.JPanel NodeInfoPanel;
    private javax.swing.JPanel NodeOptionsPanel;
    private javax.swing.JButton btn_DeleteNode;
    private javax.swing.JButton btn_EDITNAME;
    private javax.swing.JButton btn_ResetAndClose;
    private javax.swing.JButton btn_SaveAndExit;
    private javax.swing.JToggleButton btn_SetAsGoal;
    private javax.swing.JToggleButton btn_SetAsRoot;
    private javax.swing.JLabel label_ndeSize;
    private javax.swing.JLabel lbl_NodeLocation;
    private javax.swing.JLabel lbl_NodeName;
    private javax.swing.JSlider slide_ndeSlider;
    private javax.swing.JTextField txt_NodeName;
    private javax.swing.JTextField txt_NodeX;
    private javax.swing.JTextField txt_NodeY;
    private javax.swing.JTextField txt_ndeSize;
    // End of variables declaration//GEN-END:variables
}